version: '3'
#networks:
#  fastdfs-net:
#    external: true
networks:
  fastdfs-net:
    driver: bridge
services:
  tracker:
    container_name: tracker
    image: kenny14/nginx-fastdfs:v1
    command: tracker
    network_mode: host
    #networks:
    # - fastdfs-net
    volumes:   
      - /usr/local/fastdfs/tracker:/usr/local/fastdfs/tracker    
  storage0:
    container_name: storage0
    image: kenny14/nginx-fastdfs:v1
    command: storage
    network_mode: host
    #networks:
    # - fastdfs-net
    environment:
      - TRACKER_SERVER=tracker:22122
    volumes: 
      - /usr/local/fastdfs/storage:/usr/local/fastdfs/storage
  # storage1:
  #   container_name: storage1
  #   image: kenny14/nginx-fastdfs:v1
  #   command: storage
  #   network_mode: host  
  #   #networks:
  #     - fastdfs-net
  #   environment:
  #     - TRACKER_SERVER=10.1.5.85:22122
  #   volumes: 
  #     - /usr/local/fastdfs/storage:/usr/local/fastdfs/storage
  #  storage2:
  #   container_name: storage2
  #   image: kenny14/nginx-fastdfs:v1
  #   command: storage
  #   network_mode: host  
  #   #networks:
  #     - fastdfs-net  
  #   environment:
  #     - TRACKER_SERVER=10.1.5.85:22122
  #     - GROUP_NAME=group2
  #     - PORT=23000
  #   volumes: 
  #     - /usr/local/fastdfs/storage:/usr/local/fastdfs/storage 